export const ATTRACTION_ITEMS = {
    'Lucky Putt': [
        {id: 1, name: 'Hole PC'},
        {id: 2, name: 'Kiosk PC'},
        {id: 3, name: 'Server PC'},
        {id: 4, name: 'Operator PC'},
        {id: 5, name: 'Operator Tablet'},
        {id: 6, name: 'Network Rack'},
        {id: 7, name: 'Unifi Setup'},
    ],
    '6p Limitless VR': [
        {id: 1, name: 'Pico Headsets'},
        {id: 2, name: 'Pico Accessories'},
        {id: 3, name: 'Strikers'},
        {id: 4, name: 'Trackers'},
        {id: 5, name: 'Tracker Mounts'},
        {id: 6, name: 'Server PC'},
        {id: 7, name: 'Kiosk Tablet'},
        {id: 8, name: 'Operator Tablet'},
        {id: 9, name: 'Network Rack'},
        {id: 10, name: 'Unifi Setup'},
    ],
    '8p Limitless VR': [
        {id: 1, name: 'Pico Headsets'},
        {id: 2, name: 'Pico Accessories'},
        {id: 3, name: 'Strikers'},
        {id: 4, name: 'Trackers'},
        {id: 5, name: 'Tracker Mounts'},
        {id: 6, name: 'Server PC'},
        {id: 7, name: 'Kiosk Tablet'},
        {id: 8, name: 'Operator Tablet'},
        {id: 9, name: 'Network Rack'},
        {id: 10, name: 'Unifi Setup'},
    ],
    '12p Limitless VR': [
        {id: 1, name: 'Pico Headsets'},
        {id: 2, name: 'Pico Accessories'},
        {id: 3, name: 'Strikers'},
        {id: 4, name: 'Trackers'},
        {id: 5, name: 'Tracker Mounts'},
        {id: 6, name: 'Server PC'},
        {id: 7, name: 'Kiosk Tablet'},
        {id: 8, name: 'Operator Tablet'},
        {id: 9, name: 'Network Rack'},
        {id: 10, name: 'Unifi Setup'},
    ],
    'D&B Ranger Station': [
        {id: 1, name: 'Audio Cabinet'},
        {id: 2, name: 'Unifi Gateway'},
        {id: 3, name: 'Game PC'},
        {id: 4, name: 'Unifi Setup'},
    ],
    'EO Batman': [
        {id: 1, name: 'Batman Stick PCs'},
    ]
}